import numpy as np

#Mode
AUTO = 0
MANUAL = 1

#Mission en cours
HOME = 0
ALERT = 1
RETURN = 2
RONDE = 3
IN_CHARGE = 4

#Etat batterie
LOW_BATTERY = 0
HIGH_BATTERY = 1

#Ordres robot
STOP=0
NORTH=1
SOUTH=2
EAST=3
WEST=4
NORTH_WEST=5
NORTH_EAST=6
SOUTH_WEST=7
SOUTH_EAST=8
ROTATE_RIGHT=9
ROTATE_LEFT=10

#Position Balises
STAGIAIRE = 0
MANAGER = 1
PAUSE = 2
REUNION = 3
ENTREE = 4
BUREAU = 5
OPEN_SPACE_ENTREE = 6

#Dijkstra dot
DOT_STAGIAIRE = 1
DOT_MANAGER = 7
DOT_PAUSE = 8
DOT_REUNION = 9
DOT_ENTREE = 11
DOT_BUREAU = 13
DOT_OPEN_SPACE_ENTREE = 16
NOWHERE = 17

#LOC
LOC_STAGIAIRE = [0, 0]
LOC_MANAGER = [0, 0]
LOC_PAUSE = [0, 0]
LOC_REUNION = [0, 0]
LOC_ENTREE = [0, 0]
LOC_BUREAU = [0, 0]
LOC_OPEN_SPACE_ENTREE = [0, 0]

DIJKSTRA_MATCH = np.array([[STAGIAIRE, MANAGER, PAUSE, REUNION, ENTREE, BUREAU, OPEN_SPACE_ENTREE], 
                            [DOT_STAGIAIRE, DOT_MANAGER, DOT_PAUSE, DOT_REUNION, DOT_ENTREE, DOT_BUREAU, DOT_OPEN_SPACE_ENTREE]])

#Loc Home
LOC_HOME = [0, 0]
LOC_MANAGER = [0, 0]
LOC_MEETING = [0, 0]
LOC_PAUSE = [0, 0]
LOC_OFFICE = [0, 0]
LOC_OPENSPACE = [0, 0]